Repository alphatero/f2e_scrum_frontend, pull requests merged in 2023-01, with the labels that each got.

#69 feat: component - create button with Rabbit compo, fix button compo
  src/components/Button.jsx
  src/components/ButtonRabbit.jsx
  src/components/ChatRoom.jsx
  src/components/DragLayout.jsx
Labels: 大大求幫看！！！

#72 feat: BlurBlockBg component - new a type
  src/components/BlurBlockBg.jsx
  src/components/introduction/IntroductionLayout.jsx
  src/views/introduction/ProductBacklog.jsx
  src/views/introduction/Role.jsx
  src/views/introduction/SprintPoint.jsx
Labels: 大大求幫看！！！

#73 feat: 🎸 introduction productBacklog and sprint point page combine layout component
  src/components/introduction/IntroductionLayout.jsx
  src/components/introduction/Tag.jsx
  src/constants/introductionProductBacklog.js
  src/constants/introductionScrum.js
  src/constants/introductionSprintGuide.js
  src/constants/introductionSprintPoint.js
  src/views/introduction/ProductBacklog.jsx
  src/views/introduction/SprintPoint.jsx
Labels: 大大求幫看！！！, 斯巴拉西 by Pencil, 彎的佛 by 圈

#70 feat: 🎸 fixed drag will not useful issue
  src/components/DragLayout.jsx
  src/components/exam/DroppableBox.jsx
  src/components/exam/index.js
  src/utils/calculate.js
  src/utils/index.js
Labels: 大大求幫看！！！, 彎的佛 by 圈

#71 Feature: role layout 重構
  src/components/introduction/IntroductionLayout.jsx
  src/components/introduction/Role/Block.jsx
  src/components/introduction/Role/ItemChild.jsx
  src/components/introduction/Role/ItemContainer.jsx
  src/components/introduction/Role/ItemHeaderImg.jsx
  src/components/introduction/Role/ItemHeaderTitle.jsx
  src/components/introduction/Role/Triangle.jsx
  src/components/introduction/Role/index.js
  src/components/introduction/index.js
  src/views/introduction/Role.jsx
Labels: 大大求幫看！！！

#78 feat: 🎸button component remove p tag
  src/components/Button.jsx
Labels: 大大求幫看！！！, 彎的佛 by 圈
