Repository alphatero/f2e_scrum_frontend, pull requests merged in 2023-03, with the labels that each got.

#88 Feat/get api
  src/api/base.js
  src/api/index.js
Labels: 大大求幫看！！！, 彎的佛 by 圈

#87 refactor: 💡 organized components and layouts and textbubble
  src/components/Icons.jsx
  src/components/chat/ChatLog.jsx
  src/components/chat/ChatNavBar.jsx
  src/components/chat/SubmitMsg.jsx
  src/components/common/BgBubble.jsx
  src/components/common/BlurBlockBg.jsx
  src/components/common/Button.jsx
  src/components/common/Icons.jsx
  src/components/common/index.js
  src/components/exam/ArrowDownCircle.jsx
  src/components/home/TextBubble.jsx
  src/components/index.js
  src/components/introduction/ButtonRabbit.jsx
  src/components/introduction/Role/ItemContainer.jsx
  src/components/introduction/index.js
  src/components/layout/ChatRoom.jsx
  src/components/layout/CoverLayout.jsx
  src/components/layout/DragLayout.jsx
  src/components/layout/IntroductionLayout.jsx
  src/components/layout/index.js
  src/constants/homeInfo.js
  src/constants/thankInfo.js
  src/views/ThankYou.jsx
  src/views/exam/ExamProductBacklog.jsx
  src/views/index.jsx
  src/views/introduction/Role.jsx
  src/views/introduction/Scrum.jsx
  src/views/introduction/SprintGuide.jsx
Labels: 大大求幫看！！！, 彎的佛 by 圈

#77 fix: text-bubble and chat-room 調整
  src/components/chat/ChatLogMotion.jsx
  src/components/chat/index.js
  src/components/layout/ChatRoom.jsx
Labels: 還有東西要修喔, 建置中

#90 feat: 🎸 add craco and reorganize import alias
  .eslintrc.js
  craco.config.js
  package.json
  src/App.css
  src/App.jsx
  src/components/chat/ChatLog.jsx
  src/components/chat/ChatNavBar.jsx
  src/components/chat/SubmitMsg.jsx
  src/components/common/Icons.jsx
  src/components/exam/ArrowDownCircle.jsx
  src/components/introduction/ButtonRabbit.jsx
  src/components/introduction/Role/ItemContainer.jsx
  src/components/layout/CoverLayout.jsx
  src/components/layout/DragLayout.jsx
  src/components/layout/IntroductionLayout.jsx
  src/views/ThankYou.jsx
  src/views/chat/SprintDailyScrum.jsx
  src/views/chat/SprintRetro.jsx
  src/views/chat/SprintReview.jsx
  src/views/exam/ExamProductBacklog.jsx
  src/views/exam/ExamSprintPoint.jsx
  src/views/index.jsx
  src/views/introduction/ProductBacklog.jsx
  src/views/introduction/Role.jsx
  src/views/introduction/Scrum.jsx
  src/views/introduction/SprintGuide.jsx
  src/views/introduction/SprintPoint.jsx
Labels: 大大求幫看！！！
